services:
  # 1. Redis
  redis:
    image: redis:alpine
    container_name: limiter-redis
    ports:
      - "6379:6379"
    networks:
      - dsl-net

  # 2. Rate Limiter App
  app:
    container_name: rate-limiter-app
    build:
      context: ..
      dockerfile: rate-limiter/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - PORT=8081
    networks:
      - dsl-net

networks:
  dsl-net:
    external: true