{
 "title": "URL Shortener",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Request Max Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "targets": [
    { "expr": "http_requests_seconds_max", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 11, "y": 0 },
   "targets": [
    { "expr": "http_requests_seconds_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(http_requests_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}